"""Simplify user model

Revision ID: 8e86ec5c3808
Revises: c62b363236c7
Create Date: 2021-10-28 18:36:08.418853

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy import UniqueConstraint

revision = '8e86ec5c3808'
down_revision = 'c62b363236c7'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("users", table_args=(UniqueConstraint('username'),)) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False))
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('mobile_no')
        batch_op.drop_column('email')
        batch_op.drop_column('country')

    with op.batch_alter_table("keys", table_args=(UniqueConstraint('key'))):
        pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.VARCHAR(), nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), nullable=False))
    op.add_column('users', sa.Column('mobile_no', sa.VARCHAR(), nullable=False))
    op.add_column('users', sa.Column('address', sa.VARCHAR(), nullable=False))
    op.add_column('users', sa.Column('city', sa.VARCHAR(), nullable=False))

    with op.batch_alter_table("keys") as batch_op:
        batch_op.drop_constraint("key", type_="unique")

    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_constraint("username", type_="unique")

    op.drop_column('users', 'username')

    # ### end Alembic commands ###
